### ISSUE TITLE
pygpstruct_demo does not work

### ISSUE THREAD

**Issue by sdwfrost** [sebastien-bratieres/pygpstruct#1] opened 2016-02-02 23:42 UTC
I get an error when running the first implementation of `learn_predict_pygpstruct_wrapper`

```
2016-02-02 23:39:07,645Z - INFO - learn_predict_gpstruct started with arguments: {'kernel': <function kernel_linear_unary at 0x7fa063e829d8>, 'hp_sampling_mode': None, 'hp_debug': False, 'n_f_star': 0, 'prediction_thinning': 100, 'prepare_from_data': <function learn_predict_gpstruct_wrapper.<locals>.<lambda> at 0x7fa05dcaabf8>, 'hp_sampling_thinning': 1, 'prediction_verbosity': None, 'prior': 1, 'n_samples': 501, 'lhp_update': {}, 'result_prefix': '/tmp/pygpstruct_demo/', 'stop_check': None, 'random_seed': 0, 'console_log': True}
2016-02-02 23:39:07,649Z - INFO - prepare_from_data_chain started with arguments: {'native_implementation': False, 'data_folder': '/home/simon/Programs/pygpstruct/data/japanesene/', 'n_features_x': 102799, 'n_labels': 17, 'data_indices_train': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'logger': <logging.Logger object at 0x7fa0601344a8>, 'data_indices_test': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])}
2016-02-02 23:39:07,839Z - DEBUG - prepare kernel matrices
2016-02-02 23:39:07,902Z - DEBUG - start MCMC chain
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-8-0eca5a6e93f0> in <module>()
      7                                                        n_samples=501, # how many MCMC iterations
      8                                                        task='japanesene',
----> 9                                                        prediction_thinning=100
     10                                                        )

/home/simon/Programs/pygpstruct/src/prepare_from_data_chain.py in learn_predict_gpstruct_wrapper(data_indices_train, data_indices_test, task, data_folder, result_prefix, console_log, n_samples, prediction_thinning, lhp_update, kernel, random_seed, stop_check, native_implementation)
     71                            kernel=kernel,
     72                            random_seed=random_seed,
---> 73                            stop_check=stop_check
     74                            )
     75 

/home/simon/Programs/pygpstruct/src/learn_predict.py in learn_predict_gpstruct(prepare_from_data, result_prefix, console_log, n_samples, prediction_thinning, prediction_verbosity, n_f_star, hp_sampling_thinning, hp_sampling_mode, prior, lhp_update, kernel, random_seed, stop_check, hp_debug)
    187             (lower_chol_k_compact, k_star_T_k_inv) = compute_kernels(lhp)
    188 
--> 189         current_f, current_ll_train = ess_k_sampler.ESS(current_f, ll_train, lower_chol_k_compact, util.read_randoms)
    190         #read_randoms(should=current_f, true_random_source=False)
    191         #current_ll_train = read_randoms(1, should=ll_train(current_f), true_random_source=False)

/home/simon/Programs/pygpstruct/src/ess_k_sampler.py in ESS(f, logli, lower_chol_K_compact, read_randoms)
      9 #    u = np.random.rand(1)
     10 #    print("initial logli evaluation")
---> 11     log_y = numpy.log(u) + logli(f)
     12     read_randoms(1, should=log_y)
     13     read_randoms(f.shape[0], should=f)

/home/simon/Programs/pygpstruct/src/prepare_from_data_chain.py in <lambda>(f)
    103         log_likelihood_function_numba.temp_array_2 = np.empty((n_labels))
    104         return (
--> 105             lambda f : prepare_from_data.log_likelihood_dataset(f, data_train, log_likelihood_function_numba, True),
    106             lambda f : prepare_from_data.posterior_marginals(f, data_test, marginals_function),
    107             lambda marginals : compute_error_nlm(marginals, data_test),

/home/simon/Programs/pygpstruct/src/prepare_from_data.py in log_likelihood_dataset(f, dataset, log_likelihood_datapoint, ll_fun_wants_log_domain)
     72         #assert(log_node_pot.shape == (dataset.object_size, dataset.object_size, dataset.n_labels))
     73 
---> 74         ll_datapoint = log_likelihood_datapoint(node_pot, edge_pot, dataset.Y[n], dataset.object_size[n], dataset.n_labels)
     75         # if (ll_datapoint >0):
     76             # info_string = ""

/usr/local/lib/python3.4/dist-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    169         assert not kws
    170         sig = tuple([self.typeof_pyval(a) for a in args])
--> 171         return self.compile(sig)
    172 
    173     def inspect_llvm(self, signature=None):

/usr/local/lib/python3.4/dist-packages/numba/dispatcher.py in compile(self, sig)
    347                                           self.py_func,
    348                                           args=args, return_type=return_type,
--> 349                                           flags=flags, locals=self.locals)
    350 
    351             # Check typing error if object mode is used

/usr/local/lib/python3.4/dist-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library)
    663     pipeline = Pipeline(typingctx, targetctx, library,
    664                         args, return_type, flags, locals)
--> 665     return pipeline.compile_extra(func)
    666 
    667 

/usr/local/lib/python3.4/dist-packages/numba/compiler.py in compile_extra(self, func)
    364                 raise e
    365 
--> 366         return self.compile_bytecode(bc, func_attr=self.func_attr)
    367 
    368     def compile_bytecode(self, bc, lifted=(), lifted_from=None,

/usr/local/lib/python3.4/dist-packages/numba/compiler.py in compile_bytecode(self, bc, lifted, lifted_from, func_attr)
    373         self.lifted_from = lifted_from
    374         self.func_attr = func_attr
--> 375         return self._compile_bytecode()
    376 
    377     def compile_internal(self, bc, func_attr=DEFAULT_FUNCTION_ATTRIBUTES):

/usr/local/lib/python3.4/dist-packages/numba/compiler.py in _compile_bytecode(self)
    650 
    651         pm.finalize()
--> 652         return pm.run(self.status)
    653 
    654 

/usr/local/lib/python3.4/dist-packages/numba/compiler.py in run(self, status)
    249                     # No more fallback pipelines?
    250                     if is_final_pipeline:
--> 251                         raise patched_exception
    252                     # Go to next fallback pipeline
    253                     else:

/usr/local/lib/python3.4/dist-packages/numba/compiler.py in run(self, status)
    241             for stage, stage_name in self.pipeline_stages[pipeline_name]:
    242                 try:
--> 243                     res = stage()
    244                 except _EarlyPipelineCompletion as e:
    245                     return e.result

/usr/local/lib/python3.4/dist-packages/numba/compiler.py in stage_nopython_frontend(self)
    461                 self.args,
    462                 self.return_type,
--> 463                 self.locals)
    464 
    465         with self.fallback_context('Function "%s" has invalid return type'

/usr/local/lib/python3.4/dist-packages/numba/compiler.py in type_inference_stage(typingctx, interp, args, return_type, locals)
    778 
    779     infer.build_constraint()
--> 780     infer.propagate()
    781     typemap, restype, calltypes = infer.unify()
    782 

/usr/local/lib/python3.4/dist-packages/numba/typeinfer.py in propagate(self)
    563             self.debug.propagate_finished()
    564         if errors:
--> 565             raise errors[0]
    566 
    567     def add_type(self, var, tp, unless_locked=False):

TypingError: Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x7fa05dcbc9b0>:
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/numba/typeinfer.py", line 111, in propagate
    constraint(typeinfer)
  File "/usr/local/lib/python3.4/dist-packages/numba/typeinfer.py", line 284, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/usr/local/lib/python3.4/dist-packages/numba/typeinfer.py", line 311, in resolve
    sig = context.resolve_function_type(fnty, pos_args, kw_args)
  File "/usr/local/lib/python3.4/dist-packages/numba/typing/context.py", line 123, in resolve_function_type
    return func.get_call_type(self, args, kws)
  File "/usr/local/lib/python3.4/dist-packages/numba/types.py", line 425, in get_call_type
    sig.pysig = self.pysig
AttributeError: 'NoneType' object has no attribute 'pysig'
--%<-----------------------------------------------------------------

File "src/chain_forwards_backwards_logsumexp.py", line 37
```

**Comment by sebastien-bratieres** [comment] 2016-02-16 12:01
Hi, this error is related to Numba, the optimizing compiler I use to speed up numerics. 

I have tested pygpstruct with the following versions: Python 2.7.8 and 3.4.1, Numpy 1.8.1, Numba 0.13.3, on Ubuntu 12.04. 
I just reproduced this test environment to check on the issue you're reporting. I noticed I didn't mention dependencies on scipy, matplotlib, scikit-learn. I also fixed a circular definition issue with learn_predict.dtype_for_arrays (checked in now). In this test environment, all works fine.
I suspected this error could be due to a backwards-incompatible change in Numba, so I tested with an up-to-date version of Numba (0.23.1, not the one I had tested with initially), and was able to reproduce your error. 
I have now modified the source code to support this version of Numba as well. So the code should work for you now I hope.
If you would like to circumvent Numba altogether (at the cost of slower computation), you can remove all the @numba.jit or @numba.njit attributes like in prepare_from_data_chain.py line 166.

**Closed as completed by sebastien-bratieres** 2016-02-16 12:01 UTC
